blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/YakaTeam/issues/new/choose
    about: Issues and requests about the app itself should be opened in the issues repository instead
  - name: ⭐ Sources issue / request
    url: https://github.com/YakaTeam/kotatsu-parsers/issues/new/choose
    about: Issues and requests about the parsers itself should be opened in the kotatsu-parsers repository instead
